### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by seamusdemora** [alexharv074/scripts#2]
It just doesn't work... I've attached my result.
[UsefulShellTricksTest.md.zip](https://github.com/alexharv074/scripts/files/4169180/UsefulShellTricksTest.md.zip)

**Comment by alex-harvey-z3q** [comment]
@seamusdemora sorry, what doesn't work?

**Comment by seamusdemora** [comment]
Oh - sorry, I assumed you'd be able to tell from the attachment I provided. Your script to generate a TOC from a Markdown document didn't give the hoped-for results. I got a TOC, but it doesn't have hyperlinks to the headings in the document. My attachment (above) contains the .md file, and it has the TOC that your script generated pasted into it.

**Comment by alex-harvey-z3q** [comment]
@seamusdemora It looks ok to me?
```
▶ ruby ~/git/home/scripts/gen_markdown_toc.rb UsefulShellTricksTest.md
#### Table of contents

    * [Useful shell tricks:](#usefulshelltricks)
        - [1. Reload bash's .profile without restarting shell:](#1reloadbashsprofilewithoutrestartingshell)                                                                             
        - [2. Clear the contents of a file without deleting the file:](#2clearthecontentsofafilewithoutdeletingthefile)                                                                 
        - [3. List all directories - not files, just directories:](#3listalldirectoriesnotfilesjustdirectories)                                                                         
        - [4. Sequential shell command execution: ](#4sequentialshellcommandexecution)
    * [REFERENCES:](#references)
```
Are you saying you tested that and it doesn't work?

**Comment by alex-harvey-z3q** [comment]
@seamusdemora  The problem is your Markdown is using a level 3 header at the top and then level 4 headers inside. That is actually configurable inside my script:

```ruby
  def initialize(source_file, top=2, max=4)
    @source_file = source_file
    @top = top
    @max = max
    @count = 1
    @level  = ""
    @header = ""
    @start  = ""
  end
```

If I change that to top=3, max=4 it probably generates what you want:

```text
▶ ruby ~/git/home/scripts/gen_markdown_toc.rb UsefulShellTricksTest.md
#### Table of contents

1. [Useful shell tricks:](#usefulshelltricks)
    - [1. Reload bash's .profile without restarting shell:](#1reloadbashsprofilewithoutrestartingshell)                                                                                 
    - [2. Clear the contents of a file without deleting the file:](#2clearthecontentsofafilewithoutdeletingthefile)                                                                     
    - [3. List all directories - not files, just directories:](#3listalldirectoriesnotfilesjustdirectories)                                                                             
    - [4. Sequential shell command execution: ](#4sequentialshellcommandexecution)
2. [REFERENCES:](#references)
```

**Comment by seamusdemora** [comment]
This is closer, but the TOC entries don't have valid links. [See it here](https://github.com/seamusdemora/PiFormulae/edit/master/UsefulShellTricksCopy.md).

**Comment by alex-harvey-z3q** [comment]
@seamusdemora I just realised I had an unpushed bugfix. Can you try now?

**Comment by alex-harvey-z3q** [comment]
It now generates:

```
▶ ruby ~/git/home/scripts/gen_markdown_toc.rb UsefulShellTricksTest.md
#### Table of contents

    * [Useful shell tricks:](#useful-shell-tricks)
        - [1. Reload bash's .profile without restarting shell:](#1-reload-bashs-profile-without-restarting-shell)
        - [2. Clear the contents of a file without deleting the file:](#2-clear-the-contents-of-a-file-without-deleting-the-file)
        - [3. List all directories - not files, just directories:](#3-list-all-directories---not-files-just-directories)
        - [4. Sequential shell command execution: ](#4-sequential-shell-command-execution-)
    * [REFERENCES:](#references)
```

**Comment by seamusdemora** [comment]
Closer still :) 

All of the links in the TOC now work except for `4. Sequential...`

It appears to have picked up an extra `-` at the end of the link; i.e. `(#4-sequential-shell-command-execution-)`

**Comment by alex-harvey-z3q** [comment]
@seamusdemora Ok. Try now?

**Comment by seamusdemora** [comment]
Very good! 

I like the simplicity of your script - by that I mean I like that it's a single file & generates a ToC that can be pasted into my .md file. That said, I've got a couple of feature requests I'll submit if you're interested in that?

I've got several other files that need a ToC, so you may hear more from me if I encounter problems.

**Comment by alex-harvey-z3q** [comment]
@seamusdemora  You are welcome to suggest features and beyond that I can't really say if I'll want to merge them until I know what they are. I do want the script to stay simple though.

**Comment by seamusdemora** [comment]
Fair enough - I'm the same... happy to share, but only if it interests me :)

Shall we close this issue & I'll make my feature suggestion(s) in a diff thread?

**Comment by alex-harvey-z3q** [comment]
@seamusdemora Go for it!
