### ISSUE TITLE
Wish List 0

### ISSUE THREAD

**Issue by seamusdemora** [alexharv074/scripts#3]
I've used this script, and I think it's very useful. It's also simple and straightforward. I like the fact that you can use it offline. 

There are three things that I wish it would do - things it doesn't do now: 

1. Heading levels: I wish the script would figure that out for me. That might be difficult or add complexity... but I still wish for it. If that's not possible, maybe add some code to handle arguments on the cmd line? 

2. "Style" choices for TOC rendering. Two choices would probably do it for me: one that picked up the use of ordered lists, and included the numbers, another that ignored the numbers. This would be useful for me because I tend to use (over-use?) ordered lists for topics/steps when I'm creating MD docs, and sometimes shift to un-ordered lists when I need sub-topics (you can't have para. 1.a.iii in Markdown). 

3. A brief `man` page would be useful - esp. if arguments are added to the command line. A `--help` argument would also work in lieu of a `man` page.

**Comment by alex-harvey-z3q** [comment]
@seamusdemora 

1. It is not really possible to figure out the heading level because the heading level is really a choice for the author of the markdown document. Generally, I have a level 1 heading at the top of the document as the title. I don't want this to appear in my ToC. And if I have so many nested headings that I exceed level 4, then I decided I don't want my ToC cluttered with those. I suppose I could add option parsing to allow a CLI argument to set the heading level. Would that actually help you?

2. That sounds quite hard to implement I'm sorry, and I expect that the end result would be a complicated script and I don't really want that.

3. If I implemented (1) I suppose I would also implement a help option. Let me know your thoughts on (1).

**Comment by seamusdemora** [comment]
@alexharv074 

1. Understood. And yes, I feel putting a min-max/top-bottom argument would help me. 

2. Yeah - agree... it wasn't a well-considered "wish". Let me mull this one over & if I can do better, I'll float it by you again. 

3. Agree. And FWIW: I don't recall now where I saw this, but I think it was your idea: piping the script output to `pbcopy` works **really** well on macos. It's not a well-known function, so maybe that's worth mentioning in the help.

**Comment by alex-harvey-z3q** [comment]
@seamusdemora Updated in the master branch. Let me know what you think? It also could be time I moved this script to its own project. It seems popular!

**Comment by alex-harvey-z3q** [comment]
@seamusdemora fyi, I have now released this script in its own project https://github.com/alexharv074/markdown_toc Feel free to suggest further improvements, although I like the simplicity of this, and I daresay people who are writing markdown in a way that defies this script could be better off changing their markdown.

**Comment by seamusdemora** [comment]
Thanks! I'll have a look as soon as I'm able... I have a couple of files that need updated ToCs.

**Comment by seamusdemora** [comment]
Just used the [revised script](https://github.com/alexharv074/markdown_toc) on [this page.](https://github.com/seamusdemora/PiFormulae/blob/master/UsefulShellTricks.md), and it worked well. And I think you are also correct in that my *markdown writing style* needs some work! Use of **Headings** can't help but vary depending on content, but I need to tighten this up for sure. Only comment I could make on the script itself is this: I see little point in making the Title of the document an item in the ToC as it's only one line above. But there might be cases where that's useful. I edited the ToC to remove it for my document. Just a thought...

And thanks again!

**Comment by alex-harvey-z3q** [comment]
@seamusdemora I agree with you that the title is not supposed to appear in the ToC and I never saw it do that. Can you show me a document where it does that so I can fix?

**Comment by seamusdemora** [comment]
I believe it was [this page](https://github.com/seamusdemora/PiFormulae/blob/master/UsefulShellTricks.md), but I've made a couple of changes: 1. removed numbered list, 2. edited out the title. The command I used included the TOP & MAX heading defs - `3 4` IIRC. Let me know if you can't reproduce that & I'll dig into my history files deeper.

**Comment by alex-harvey-z3q** [comment]
@seamusdemora yes, agreed. I just fixed that and there's a version 1.0.2 out you can use.
